#!/bin/bash

make_version() {
  echo -e "<!-- WARNING: This is an autogenerated file!\n              To make changes, modify 'head.html' and/or 'rest.html'. -->\n" > $2.html
  cat head.html >> $2.html
  echo "    <body id=\"$1\">" >> $2.html
  cat rest.html >> $2.html
}

make_version "control" "10"
make_version "half" "11"
make_version "full" "12"
