#!/usr/bin/env python3

import sys
import correctness as c
from common import Node

code = sys.stdin.read()

try:
    exec(code, globals())

    if c.check(c.true_insert, insert, True):
        print("true")
    else:
        print("false")
except:
    print("false")
