#!/usr/bin/env python3

import sys
"""
def search(root, key):
    if [ReturnTrue]:
        return True
    if [MoveLeft]:
        return search(root.left, key)
    if [MoveRight]:
        return search(root.right, key)
    return False
"""

# TODO For now, just echo out the input
print(sys.stdin.read())
